package studioproject.entity;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.bean.ViewScoped;
import studioproject.dao.ContattiDao;

/**
 * Contatti generated by hbm2java
 */

@ManagedBean
@SessionScoped
public class ListaContatti implements java.io.Serializable {

   @ManagedProperty("#{dettaglioContatto}")
   private DettaglioContatto dettaglioContatto;
    
   @ManagedProperty("#{currentUserBean}")
   private CurrentUserBean currentUserBean; 
   
   CurrentUserBean usercorrente;
   

    public ListaContatti() {
    }

    public DettaglioContatto getDettaglioContatto() {
        return dettaglioContatto;
    }

    public void setDettaglioContatto(DettaglioContatto dettaglioContatto) {
        this.dettaglioContatto = dettaglioContatto;
    }

    public CurrentUserBean getCurrentUserBean() {
        return currentUserBean;
    }

    public void setCurrentUserBean(CurrentUserBean currentUserBean) {
        this.currentUserBean = currentUserBean;
    }

  

    

    
    public List<Contatti> getallrecords()
{
    ContattiDao cdao=new ContattiDao();
    List<Contatti> cont=cdao.retrieveContatti();
    return cont;
}
    
    
 public String editSelezionato (int id){
        
       ContattiDao cdao=new ContattiDao();
        
        dettaglioContatto.setContatto(cdao.getContatto(id));
        return "dettaglioContatto";
    }
    
public String deleteSelezionato (int id){
       
       ContattiDao cdao=new ContattiDao();
        cdao.cancellaContatto(id);
        
        return "listaContatti";
    }

    public CurrentUserBean getUsercorrente() {
        return usercorrente;
    }

    public void setUsercorrente(CurrentUserBean usercorrente) {
        this.usercorrente = usercorrente;
    }





public String inserisci (){
        
      
        
        return "nuovoContatto";
    }
 
}