package studioproject.entity;
// Generated 28-apr-2016 11.09.40 by Hibernate Tools 4.3.1

import java.util.List;
import studioproject.dao.ContattiDao;




/**
 * RapportiDiLavoro generated by hbm2java
 */
public class RapportiDiLavoro  implements java.io.Serializable {


     private Integer id;
     private Contatti contatti;
     private String nomeAzienda;
     private String mansione;

    public RapportiDiLavoro() {
    }

	
    public RapportiDiLavoro(Contatti contatti, String nomeAzienda) {
        this.contatti = contatti;
        this.nomeAzienda = nomeAzienda;
    }
    public RapportiDiLavoro(Contatti contatti, String nomeAzienda, String mansione) {
       this.contatti = contatti;
       this.nomeAzienda = nomeAzienda;
       this.mansione = mansione;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Contatti getContatti() {
        return this.contatti;
    }
    
    public void setContatti(Contatti contatti) {
        this.contatti = contatti;
    }
    public String getNomeAzienda() {
        return this.nomeAzienda;
    }
    
    public void setNomeAzienda(String nomeAzienda) {
        this.nomeAzienda = nomeAzienda;
    }
    public String getMansione() {
        return this.mansione;
    }
    
    public void setMansione(String mansione) {
        this.mansione = mansione;
    }




}


