package studioproject.entity;
// Generated 28-apr-2016 11.09.40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TypoTitoliDiStudio generated by hbm2java
 */
public class TypoTitoliDiStudio  implements java.io.Serializable {


     private Integer id;
     private String titolo;
     private Set contattis = new HashSet(0);

    public TypoTitoliDiStudio() {
    }

	
    public TypoTitoliDiStudio(String titolo) {
        this.titolo = titolo;
    }
    public TypoTitoliDiStudio(String titolo, Set contattis) {
       this.titolo = titolo;
       this.contattis = contattis;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitolo() {
        return this.titolo;
    }
    
    public void setTitolo(String titolo) {
        this.titolo = titolo;
    }
    public Set getContattis() {
        return this.contattis;
    }
    
    public void setContattis(Set contattis) {
        this.contattis = contattis;
    }




}


