package studioproject.entity;
// Generated 28-apr-2016 11.09.40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Utenti generated by hbm2java
 */
public class Utenti  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String username;
     private String password;
     private Set contattis = new HashSet(0);

    public Utenti() {
    }

	
    public Utenti(String nome, String username, String password) {
        this.nome = nome;
        this.username = username;
        this.password = password;
    }
    public Utenti(String nome, String username, String password, Set contattis) {
       this.nome = nome;
       this.username = username;
       this.password = password;
       this.contattis = contattis;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getContattis() {
        return this.contattis;
    }
    
    public void setContattis(Set contattis) {
        this.contattis = contattis;
    }




}


